# Generated by Django 4.2.6 on 2023-11-10 18:03

from django.db import migrations, models
import player.models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playermodel',
            options={'ordering': ['username']},
        ),
        migrations.AddField(
            model_name='playermodel',
            name='avatar',
            field=models.ImageField(blank=True, upload_to=player.models.user_profile_image_path),
        ),
    ]
