# Generated by Django 4.2.6 on 2023-12-01 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0002_alter_playermodel_options_playermodel_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playermodel',
            name='aka',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='AKA'),
        ),
    ]
