# Generated by Django 4.2.6 on 2023-12-01 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0003_alter_playermodel_aka'),
    ]

    operations = [
        migrations.AddField(
            model_name='playermodel',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
