# Generated by Django 4.2.6 on 2023-10-14 00:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('match', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultmodel',
            name='losers',
            field=models.ManyToManyField(blank=True, related_name='losers', to=settings.AUTH_USER_MODEL, verbose_name='Lossers'),
        ),
        migrations.AddField(
            model_name='resultmodel',
            name='winners',
            field=models.ManyToManyField(blank=True, related_name='winners', to=settings.AUTH_USER_MODEL, verbose_name='Winners'),
        ),
        migrations.AddField(
            model_name='matchmodel',
            name='players',
            field=models.ManyToManyField(blank=True, related_name='players', to=settings.AUTH_USER_MODEL, verbose_name='Match Players'),
        ),
        migrations.AddField(
            model_name='matchmodel',
            name='result',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='result', to='match.resultmodel', verbose_name='Result'),
        ),
        migrations.AddField(
            model_name='matchmodel',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='match', to='match.sessionmodel', verbose_name='Session'),
        ),
    ]
